# Generated by Django 4.0.3 on 2022-04-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='department1',
        ),
    ]
