# Generated by Django 4.0.1 on 2022-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0002_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TakingAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('reg', models.CharField(max_length=255)),
                ('deapartment_name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('period_1', models.CharField(max_length=255)),
                ('period_2', models.CharField(max_length=255)),
                ('period_3', models.CharField(max_length=255)),
                ('period_4', models.CharField(max_length=255)),
                ('period_5', models.CharField(max_length=255)),
                ('period_6', models.CharField(max_length=255)),
                ('period_7', models.CharField(max_length=255)),
                ('period_8', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
