# Generated by Django 4.0.1 on 2022-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Teacher',
        ),
    ]
