# Generated by Django 4.0.1 on 2022-04-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_department_rename_name_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deptName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_app.department'),
        ),
    ]
