# Generated by Django 4.0.1 on 2022-04-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
