# Generated by Django 4.0.1 on 2022-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_department_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='department',
        ),
        migrations.AddField(
            model_name='attendence',
            name='Student_department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='attendence',
            name='Teacher_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
